version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
    env_file:
      - compose/.env_prod
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/blockscan.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    env_file:
      - compose/.env_prod
    depends_on:
      - postgres
    volumes:
      - ./:/code
  redis:
    image: "redis:alpine"